### ISSUE TITLE
"There is no data provider registered that can provide view data."

### ISSUE THREAD

**Issue by learning-more** [blakedietz/vscode-nested-tags#16]
The "Tag Tree" area is showing the error: 

> There is no data provider registered that can provide view data.

My steps:
1. Installed the extension, and reloaded VSCode.
2. Verified the extension loaded in the Command > Show Logs.. > Extension Host log file. 
3. Created file named xxxxxxxxxx.md and verifyed the file has MD syntax.

Added the text: 
> 

The above error appears.

Troubleshooting:
Uninstalled, reinstalled.
Disabled, enabled and reloaded.

**Comment by learning-more** [comment]
The "There is no data provider" error seems to be related to the extension not loading per this [SO thread](https://stackoverflow.com/questions/30765782/the-use-of-developer-tools-in-vs-code).

Opening the Dev Tools Console, I saw this error:
> console.ts:134 [Extension Host] Activating extension `vscode-nested-tags.vscode-nested-tags` failed:  ENOENT: no such file or directory, stat '/Users/xxx/Development/xxx/include/fpdf'

Checking the fpdf file on my Mac, ls shows it is a symlink:
>$ ls -al fpd*
>$ lrwxr-xr-x  1 xxxxx    20 Jan 23 15:41 fpdf -> ../../lib/fpdf-v160/

So, I changed my workspace and added my Desktop folder, which has no symlinks.

The following errors appeared in the Dev Tools console:
> Activating extension 'vscode-nested-tags.vscode-nested-tags' failed: errmap.get is not a function or its return value is not iterable.

and

> [Extension Host] Activating extension 'vscode-nested-tags.vscode-nested-tags' failed: errmap.get is not a function or its return value is not iterable.

and

>[Extension Host] Here is the error stack:  TypeError: errmap.get is not a function or its return value is not iterable
	at Object.uvException (internal/errors.js:246:34)
	at handleErrorFromBinding (fs.js:141:24)
	at Object.fs.openSync (fs.js:577:3)
	at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
	at Object.fs.readFileSync (fs.js:483:33)
	at Object.exports.wrapFsWithAsar.fs.readFileSync (ELECTRON_ASAR.js:563:29)
	at TagTreeDataProvider.getTagsFromFileOnFileSystem (/Users/xxx/.vscode/extensions/vscode-nested-tags.vscode-nested-tags-1.0.2/out/tag-tree-data-provider.js:189:44)
	at new TagTreeDataProvider (/Users/xxx/.vscode/extensions/vscode-nested-tags.vscode-nested-tags-1.0.2/out/tag-tree-data-provider.js:36:35)
	at new TagTreeView (/Users/xxx/.vscode/extensions/vscode-nested-tags.vscode-nested-tags-1.0.2/out/tag-tree-view.js:8:31)
	at activate (/Users/xxx/.vscode/extensions/vscode-nested-tags.vscode-nested-tags-1.0.2/out/extension.js:8:5)
	at Function.t._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:741:354)
	at Function.t._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:741:25)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:740:206
